### PR TITLE
Added support for ordered to-many relationships

### PR DESCRIPTION
**Pull request by dehydr8**
I have added basic support for ordered many-to-many relationships.
The relationship table now contains two more fields that store the order of the element. Please review it and let me know if it needs any changes.

### CODE REVIEW

**Comment by dehydr8** [comment]
This pull request fixes #157

**Comment by dehydr8** [comment]
Don't merge this, still has edge cases where it would mess up the ordering

**Comment by gavin-black** [comment]
Hi @dehydr8 ,

Should we go ahead and pull this code?  It seems to be passing our test cases, but wasn't sure if you'd had a chance to fix the edge cases you mentioned? 

Thanks

Gavin

**Comment by dehydr8** [comment]
@gavin-black  Yes, please go ahead.

**Comment by gavin-black** [comment]
@dehydr8 Great!  Appreciate your contribution to the project, glad to see ordered relationships working better now

**Pull request merged**
