### PR TITLE
Drop indices and migrate relationship columns

### PR DESCRIPTION
**Pull request by jcarroll3**
Added a helper to drop indicies because migrations were failing when trying to recreate indicies.
Noticed relationship data wasn't being copied over, so added it back in with a couple of tweaks we needed.

First major edit to project, but as we needed migration we made what we feel are minimum adjustments to get it going.

### CODE REVIEW

**Comment by yousefhamza** [comment]
The worst scenario just happened, I didn't have this issue when trying to testing updating my app with migration and it went smoothly -have to try a better strategy in testing that tho..- Then I released and now I got issues in my production!

**Comment by jasper-chan** [comment]
@yousefhamza Can you explain what sort of issues you are experiencing? That will help the community a lot in resolving this issue to make ECD better.

**Comment by jasper-ch-chan** [comment]
@yousefhamza Can you please explain what sort of problems you are experiencing? It will help the community understand and thereby, improve ECD better.

**Comment by yousefhamza** [comment]
I preformed a lightweight migration on my coredate setup, and now It crashes because it says that the password is incorrect yet it's the correct password

The password and lightweight migration parameters are sent in 'options' when making store

**Comment by jasper-ch-chan** [comment]
@yousefhamza Is it safe to assume you are able to open pre-existing databases without migrating them?

**Comment by yousefhamza** [comment]
Yes
some predicates will fail later but yea.

**Comment by Hema1Latha** [comment]
How to fix the incorrect Passcode Error for migrating the CoreData

**Pull request merged**
