### PR TITLE
enable string comparison options

### PR DESCRIPTION
**Pull request by b-andris**
enabled case sensitive string comparison
enabled case insensitive string comparison
enabled diacritics insensitive string comparison

### CODE REVIEW

**Comment by gavin-black** [comment]
Hi @b-andris 

It seems this is failing to build according to Travis.  Not sure if it's a conflict with a recent merge, or something else.  Let me know if you have any idea why.  

Thanks,

Gavin

**Comment by b-andris** [comment]
@gavin-black

From what I can tell the sqlite3.h used by the build server is incomplete (doesn't include #define SQLITE_DETERMINISTIC    0x800). I created the pull request after it passed all tests on my local machine and then had to rush off for a meeting. I'll try to work it out, although I'm not to sure where to look...

Do you prefer I close the pull request in the meantime?

**Comment by gavin-black** [comment]
@b-andris 

No worries about closing it, helps me keep track of the fact that it's still outstanding.

**Comment by b-andris** [comment]
I now just check wether SQLITE_DETERMINISTIC is defined. According to my reading of SQLCiphers sqlite3.c this should work. Although the fact that apparently don't expect the encoding to be ored with anything else does slightly worry me. (Could in principle lead to problems when compiling with standard sqlite3.h)

But on the other hand this solution would not require any changes once they add support for SQLITE_DETERMINISTIC.

**Comment by dorada** [comment]
I don't feel confident to merge this into master myself, any chance you can re-base this on the current master?

**Pull request merged**
