### PR TITLE
Add entity type condition once for where clause

### PR DESCRIPTION
**Pull request by pperepelkin**
Moved adding entity type condition to where clause from recursive method not to add it multiple times for compound predicate.

### CODE REVIEW

**Comment by dorada** [comment]
Hi thanks for your PR.

Did PR #214 already solve this issue?

**Comment by pperepelkin** [comment]
Hi. PR #214 relates to other issues and didn't solve this

**Comment by pperepelkin** [comment]
I rebased my commit, it can be merged now without conflicts

**Comment by dorada** [comment]
Thanks, i'll take a look shortly

**Pull request merged**
