### PR TITLE
Set existing sqlite file with options given by user

### PR DESCRIPTION
**Pull request by jasper-ch-chan**
Reference issue #183

### CODE REVIEW

**Comment by sahara108** [comment]
This fix does not cover all cases. You should put it outside if-else
It should become like this:

        if(dburl != nil) {
        if ([dburl isKindOfClass:[NSString class]]){
            databaseURL = [NSURL URLWithString:[options objectForKey:EncryptedStoreDatabaseLocation]];
            backup = NO;
        }
        else if ([dburl isKindOfClass:[NSURL class]]){
            databaseURL = dburl;
            backup = NO;
        }
        
        if (databaseURL) {
            [[NSFileManager defaultManager] setAttributes:options ofItemAtPath:[ databaseURL absoluteString] error:nil];
        }
    }

**Comment by gavin-black** [comment]
Hi @jasper-ch-chan 

Do you think this still should be pulled in?  I'm worried it's diverged significantly since I waited too long to get to it.  I can pull it down and do the merge by hand though if you think it should still go in.

Thanks,

Gavin

**Comment by jasper-ch-chan** [comment]
@gavin-black If its not too much trouble, I feel like this should be pulled in. If a user wishes to change the options for their database, they would expect the database to be updated automatically.

**Comment by gavin-black** [comment]
And done, thanks for reminding me

**Pull request merged**
